name: CI

on: [push]

env:
  DJANGO_APPLICATION_ENVIRONMENT: test
  POSTGRES_DB: valorem
  POSTGRES_USER: valorem
  POSTGRES_PASSWORD: valorem

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.0-alpine
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
  
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
  
      - name: Install Dependencies
        run: |
          pwd
          cd api
          pwd
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Wait for PostgreSQL to become ready
        run: |
          sudo apt-get install -y postgresql-client
          until pg_isready -h localhost -p 5432; do sleep 2; done
  
      - name: Run Migrations
        run: |
          pwd
          cd api
          pwd
          sleep 10  # Wait for PostgreSQL to start
          python manage.py migrate
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          
      - name: List Tables
        run: |
          echo ${{ env.POSTGRES_PASSWORD }} | psql -h localhost -U ${{ env.POSTGRES_USER }} -d ${{ env.POSTGRES_DB }} -c '\dt'
          
      - name: Run Tests
        run: |
          pwd
          cd api
          pwd
          pytest --cov
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
