name: CI

on: [push]

env:
  DJANGO_APPLICATION_ENVIRONMENT: test
  POSTGRES_DB: valorem
  POSTGRES_USER: valorem
  POSTGRES_PASSWORD: valorem
  POETRY_NO_INTERACTION: 1
  POETRY_VIRTUALENVS_CREATE: 'false'

jobs:
  lint:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          python-version: ["3.12"]
      
      steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          cd api
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with test

      - name: Lint code
        run: |
          cd api
          flake8

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    services:
      postgres:
        image: postgres:12.0-alpine
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
  
      - name: Install Dependencies
        run: |
          cd api
          python -m pip install --upgrade pip
          pip install --upgrade setuptools
          pip install poetry
          poetry install --with test
  
      - name: Wait for PostgreSQL to become ready
        run: |
          sudo apt-get install -y postgresql-client
          until pg_isready -h localhost -p 5432; do sleep 2; done
  
      - name: Run Migrations
        run: |
          cd api
          python manage.py migrate
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
              
      - name: Run Tests
        run: |
          cd api
          pytest --cov
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
